SELECT DISTINCT DIRECTOR FROM movies order by Director ASC; 
SELECT * FROM Movies ORDER BY Year DESC LIMIT 4 
SELECT * FROM Movies ORDER BY Title ASC LIMIT 5 
SELECT DISTINCT * FROM Movies ORDER BY Title ASC LIMIT 5 OFFSET 5 




